### ISSUE TITLE
Create release supporting current Elixir version

### ISSUE THREAD

**Issue by martin-langhoff** [smpallen99/exrm-rpm#12]
Hi @smpallen99 ! The latest release does not work with current Elixir versions (ie: 1.2.2) (fails due to use of deprecated/removed `atom_to_binary` & `binary_to_atom`).

Top of current master (using `4a13306d278db758690aa28e360f1f31ae6c6343` at this time) seems to work well. However it is not released.

It'd be good to have a release tagged to save folks the pain of trying to use `0.3.0` and then realizing that `master` has the goods.

Thank you!

**Comment by smpallen99** [comment]
Runs with the latest elixir.

**Comment by martin-langhoff** [comment]
\o/ :-)
