### ISSUE TITLE
Question: exrm_rpm results in warning as not listed as application?

### ISSUE THREAD

**Issue by holsee** [smpallen99/exrm-rpm#14]
A question relating to how mix build process warns exrm_rpm is not added as application.. as it shouldn't be added as one afaik.

```
$ MIX_ENV=prod mix release --rpm
```

Before the release build I am prompted with the following warning:
```
Building release with MIX_ENV=prod.

You have dependencies (direct/transitive) which are not in :applications!
The following apps should to be added to :applications in mix.exs:

        exrm_rpm => exrm_rpm is missing from grid_replay

Continue anyway? Your release may not work as expected if these dependencies are required!
```

Is this a dev only dependency? If so, how would I create a production rpm build without being prompted?
Should exrm_rpm be added as an application as the warning suggests? I think not
Is there something that exrm sets, in order to not be confused with an application dependency?

**Comment by smpallen99** [comment]
add `warn_missing: false` to the dependency like this: 

```
  defp deps do
    [{:exrm_rpm, "~> 0.3.3", warn_missing: false}]
  end
```

And that will remove the warning. I'll update the README file.
